### ISSUE TITLE
.qua read crashes if no song preview is set

### ISSUE THREAD

**Issue by IceDynamix** [Eve-ning/reamberPy#30]
Any map in Quaver that has never had a song preview set before will make reamber raise a KeyError. Similar errors may occur with the other file formats or keys as well.

```py
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import reamber
>>> qua = reamber.quaver.QuaMap.readFile("test.qua") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\env\lib\site-packages\reamber\quaver\QuaMap.py", line 49, in readFile
    self._readMetadata(file)
  File "...\env\lib\site-packages\reamber\quaver\QuaMapMeta.py", line 55, in _readMetadata
    self.songPreviewTime    = d['SongPreviewTime']
KeyError: 'SongPreviewTime'
```

Simplest solution would be to implement following for that section

```py
self.songPreviewTime = d.get('SongPreviewTime', self.songPreviewTime)
```

**Comment by Eve-ning** [comment]
Fixed, gracias
