### ISSUE TITLE
0.0x Quaver SVs generate KeyError

### ISSUE THREAD

**Issue by IceDynamix** [Eve-ning/reamberPy#34]
Whenever a value is 0, the value is skipped in the yaml generation. If a SV of 0.0x is used, then no Multiplier is given.
```
Traceback (most recent call last):
  File "qua2osu.py", line 287, in <module>
    main()
  File "qua2osu.py", line 273, in main
    convertQp(file, outputPath, options)
  File "qua2osu.py", line 177, in convertQp
    qua = QuaMap.readFile(filePath)
  File "C:\Users\Ice\AppData\Local\Programs\Python\Python37-32\lib\site-packages\reamber\quaver\QuaMap.py", line 48, in readFile
    self._readSVs(file.pop('SliderVelocities'))
  File "C:\Users\Ice\AppData\Local\Programs\Python\Python37-32\lib\site-packages\reamber\quaver\QuaMap.py", line 78, in _readSVs
    self.svs.append(QuaSv(offset=sv['StartTime'], multiplier=sv['Multiplier']))
KeyError: 'Multiplier'
```
Simple fix would be to use `multiplier=sv.get('Multiplier', 0)`.

**Comment by Eve-ning** [comment]
Does quaver not generate the line? Or does YAML not create the entry?

If it's the latter, I'll convert all possibly `0` entries on my side

**Comment by IceDynamix** [comment]
YAML does not create the entry. Here's the qua (cut) to test.

```yaml
AudioFile: audio.mp3
SongPreviewTime: 49242
BackgroundFile: doki doki forever.jpg
MapId: 25798
MapSetId: 3318
Mode: Keys4
Title: Doki Doki Forever (ft. rachie, Chi-chi, Kathy-chan*)
Artist: OR3O
Source: Doki Doki Literature Club!
Tags: ddlc team salvato sayori yuri natsuki just monika trap dance edm
Creator: MocaLoca
DifficultyName: Just Moca
Description: Created at 1600100279000
EditorLayers: []
CustomAudioSamples: []
SoundEffects: []
TimingPoints:
- StartTime: 2970
  Bpm: 165
SliderVelocities:
- StartTime: 95969.9765625
- StartTime: 96333.625
  Multiplier: 1
HitObjects:
- StartTime: 2970
  Lane: 1
  KeySounds: []
- StartTime: 2970
  Lane: 4
  KeySounds: []
- StartTime: 3151
  Lane: 1
  KeySounds: []
- StartTime: 3515
  Lane: 1
  KeySounds: []
- StartTime: 3697
  Lane: 1
  KeySounds: []
- StartTime: 3697
  Lane: 4
  KeySounds: []
- StartTime: 3879
  Lane: 1
  KeySounds: []
- StartTime: 4242
  Lane: 1
  KeySounds: []
- StartTime: 4424
  Lane: 1
  KeySounds: []
- StartTime: 4424
  Lane: 4
  KeySounds: []
- StartTime: 4606
  Lane: 1
  KeySounds: []
# ...
```

**Comment by IceDynamix** [comment]
Speaking of 0.0x SV, is the algorithm considering 0x when converting to osu? Should probably replace with 0.01x.

**Comment by Eve-ning** [comment]
Added safe loading 6371d07758c33257986a69ed89aacec762a777ab

**Comment by Eve-ning** [comment]
Best if Quaver explicitly writes `Multiplier: 0.0`, seems unintended but I'll create that failsafe
